### ISSUE TITLE
Latex example does not work

### ISSUE THREAD

**Issue by spoorendonk** [pawamoy/mkdocstrings#87] opened 2020-04-15 07:56 UTC
**Please open an issue on [pytkdocs](https://github.com/pawamoy/pytkdocs/issues) instead
if this is related to Python docstrings parsing or the collection of Python objects!**

Not sure, but the string is passed as raw with `r`, so I think it is an mkdocstring issue?

**Describe the bug**
Running example from https://pawamoy.github.io/mkdocstrings/troubleshooting/#latex-in-docstrings-is-not-rendered-correctly gives the following error

```sh
INFO    -  Building documentation... 
ERROR   -  mkdocstrings.extension: mismatched tag: line 59, column 6 (character d):
    </div>
If your Markdown contains angle brackets < >, try to wrap them between backticks `< >`, or replace them with &lt; and &gt; 
```

This is also true for the inline version, e.g., ```$`f(x) = 2x`$```

**To Reproduce**
A mkdocstring project referencing math function in docstrings.

**Expected behavior**
The markdown-katex rendering of the latex.

**Information (please complete the following information):**
markdown-katex             202001.13b0 
MarkupSafe                 1.1.1       
mkdocs                     1.1         
mkdocs-material            5.1.0       
mkdocs-material-extensions 1.0b1       
mkdocstrings               0.10.3

**Comment by pawamoy** [comment] 2020-04-15 12:18
I was able to reproduce. I'm not sure why XML says tag mismatched on a closing `div`. I'm looking at the generated HTML and all the tags are correctly closed.

**Comment by pawamoy** [comment] 2020-04-15 13:09
The debugging was fun! I saw that `XML(str(BeautifulSoup(generated_html)))` was working welll, so I took the original HTML, the soup'd one, prettified them both on DuckDuckGo (type `prettify html`) to reduce their differences, and compared them with `difflib.Differ.compare`.

Finally, the mismatched is due to `markdown-katex` not closing its `link` tag:

```html
<link crossorigin="anonymous" href="https://cdn.jsdelivr.net/npm/katex@0.10.2/dist/katex.css" integrity="sha256-SSjvSe9BDSZMUczwnbB1ywCyIk2XaNly9nn6yRm6WJo=" rel="stylesheet">
```

This fixes it (` /` at the end):

```html
<link crossorigin="anonymous" href="https://cdn.jsdelivr.net/npm/katex@0.10.2/dist/katex.css" integrity="sha256-SSjvSe9BDSZMUczwnbB1ywCyIk2XaNly9nn6yRm6WJo=" rel="stylesheet" />
```

**Comment by pawamoy** [comment] 2020-04-15 13:12
I opened the corresponding issue on `markdown-katex`: https://gitlab.com/mbarkhau/markdown-katex/-/issues/4

**Comment by pawamoy** [comment] 2020-04-23 16:54
Fixed in markdown-katex, closing!

**Closed by pawamoy** 2020-04-23 16:54 UTC
