### ISSUE TITLE
How do I run mkdocstrings

### ISSUE THREAD

**Issue by HuiiBuh** [pawamoy/mkdocstrings#45] opened 2020-02-19 18:23 UTC
Hey I am sorry if this is a stupid question, but how do I run mkdocstrings?  
Typing `mkdocstrings` into the terminal only leads to an error...

![image](https://user-images.githubusercontent.com/46561026/74862765-003ff480-534d-11ea-93f4-e8540bcbac15.png)

**Comment by pawamoy** [comment] 2020-02-19 22:49
Ah, yes, there's an entry point defined in pyproject.toml that should be removed.

Mkdoc

**Comment by HuiiBuh** [comment] 2020-02-21 18:10
I am sorry to bother you again, but running `mkdocs build` does not generate any docs except the 404...
This is my mkdocs.yml

```yml
site_name: "Async Spotify"
docs_dir: "docs"

theme:
  name: "material"

plugins:
  - search
  - mkdocstrings:
      watch:
        - src/async_spotify
```

**Comment by pawamoy** [comment] 2020-02-23 13:06
You're not bothering me at all :slightly_smiling_face: 

- what is the contents of your markdown file containing an autodoc instruction (something like `::: python.dotted.path`)?
- is the object you want to generate documentation for available in the Python path? (the object's module must be importable, etc.)
- did you install mkdocs **and** mkdocstrings in your virtualenv?
- could you link to a project that would allow me to reproduce the issue?

**Comment by HuiiBuh** [comment] 2020-02-25 12:24
I have done all of that but get another exception this time.
![image](https://user-images.githubusercontent.com/46561026/75247407-2690e480-57d2-11ea-804e-ccd7ab07da58.png)


[Here](https://github.com/HuiiBuh/AsyncSpotify) is the link to my repo

**Comment by MariusSpangenberger** [comment] 2020-02-25 13:54
I'm currently stuck with the same issue as @HuiiBuh . Help appreciated.

mkdocs.yml:

```
nav:
...
  - Reference:
    - evaluation.py: "reference/evaluation.md"

plugins:
  - search
  - mkdocstrings
```

`docs/reference/evaluation.md` just contains the reference:
```
::: module.evaluation
```

```
Error:
 mkdocs serve
INFO    -  Building documentation... 
INFO    -  Cleaning site directory 
ERROR   -  Error reading page 'reference/evaluation.md': string indices must be integers 
Traceback (most recent call last):
  File "/usr/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
  File "/usr/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/mkdocs/__main__.py", line 143, in serve_command
    **kwargs
  File "/usr/lib/python3.7/site-packages/mkdocs/commands/serve.py", line 141, in serve
    config = builder()
  File "/usr/lib/python3.7/site-packages/mkdocs/commands/serve.py", line 136, in builder
    build(config, live_server=live_server, dirty=dirty)
  File "/usr/lib/python3.7/site-packages/mkdocs/commands/build.py", line 274, in build
    _populate_page(file.page, config, files, dirty)
  File "/usr/lib/python3.7/site-packages/mkdocs/commands/build.py", line 178, in _populate_page
    'page_content', page.content, page=page, config=config, files=files
  File "/usr/lib/python3.7/site-packages/mkdocs/plugins.py", line 94, in run_event
    result = method(item, **kwargs)
  File "/usr/lib/python3.7/site-packages/mkdocstrings/plugin.py", line 143, in on_page_content
    page.toc = get_toc(getattr(md, "toc", ""))
  File "/usr/lib/python3.7/site-packages/mkdocs/structure/toc.py", line 11, in get_toc
    toc = [_parse_toc_token(i) for i in toc_tokens]
  File "/usr/lib/python3.7/site-packages/mkdocs/structure/toc.py", line 11, in <listcomp>
    toc = [_parse_toc_token(i) for i in toc_tokens]
  File "/usr/lib/python3.7/site-packages/mkdocs/structure/toc.py", line 59, in _parse_toc_token
    anchor = AnchorLink(token['name'], token['id'], token['level'])
TypeError: string indices must be integers
```

**Comment by pawamoy** [comment] 2020-02-25 14:31
This last error happens because of the new version 1.1 of mkdocs. I'll fix mkdocstrings code, meanwhile you can pin mkdocs to 1.0.4.

**Comment by mSpangenberger** [comment] 2020-02-25 15:23
Thanks, that resolves the issues for now.

Do you have a minimal working example somewhere? I had a look around this repo and tried to mimic the structure. I wasn't able to display docstrings from Pythonfiles on a page yet. 

Shouldn't the `mkdocs.yml` and `evaluation.md` from above together with
```
"""This is my function.

    It references [another function][package.submodule.function].
    It also references another object directly: [package.submodule.SuperClass][].

"""
```
added at the top of the `module/evaluation.py` file be enough to display something on a mkdocs page?

**Comment by pawamoy** [comment] 2020-02-25 19:17
It definitely should be enough.

@HuiiBuh I cloned your repo locally, created a venv, installed the dependencies, with mkdocs==1.0.4 and then ran `mkdocs serve`, and I get this:
![Screenshot_2020-02-25_20-17-18](https://user-images.githubusercontent.com/3999221/75279272-97a0be00-580b-11ea-9770-294a4a25768f.png)
So it seems to work fine?

What system are you on @HuiiBuh, @mSpangenberger?

**Comment by HuiiBuh** [comment] 2020-02-25 19:34
Thank you. With mkdocs 1.0.4 it is working perfect.

I am running Linux Mint 19.3 Cinnamon with the 5.3.0-40-generic Linux Kernel.

**Comment by mSpangenberger** [comment] 2020-02-25 20:42
Solus with Python 3.7

**Comment by pawamoy** [comment] 2020-02-25 20:44
@mSpangenberger can you try again with the latest commit? You can also share a link to your repo so I can try it locally :slightly_smiling_face:

**Comment by mSpangenberger** [comment] 2020-02-25 20:56
Sure, I can switch back to the lastest `mkdocs `as well right.

I'm not using it with a public repo right now, I can setup an example though.

**Comment by pawamoy** [comment] 2020-02-25 21:15
It works just fine on my end :confused: 

![Screenshot_2020-02-25_22-16-52](https://user-images.githubusercontent.com/3999221/75288266-49e08180-581c-11ea-85ce-32efb89a4bcc.png)

**Comment by mSpangenberger** [comment] 2020-02-25 21:34
I'm super confused right now,

I rebuild `mkdocstrings` with your latest commit, and installed `mkdocs 1.0.4`.
Now when i run `mkdocs serve` in `example` (project you just pulled) I get the following:
![image](https://user-images.githubusercontent.com/35237005/75289544-cbd1aa00-581e-11ea-8d5e-fa4f880af3e8.png)

The shown code is not part of the project, to me it looks like something cached in mkdocs? It stays the same with restarting the server and refreshing the page.

**Comment by pawamoy** [comment] 2020-02-25 21:37
Hahaha, extra weird, it's a sentence coming directly from `mkdocstrings`'s own examples! It really should not appear here.

**Comment by pawamoy** [comment] 2020-02-25 21:38
> Apparently ::: neuronal_network.network in the .md file is referencing to the installed package on my systen but not to the directory in the project?

Depends on your Python path I think? `mkdocstrings` imports the objects, so depending on the Python path it will import it from the `site-packages` directory or from your source code.

**Comment by mSpangenberger** [comment] 2020-02-25 21:42
> For your example I ran `PYTHONPATH=. mkdocs serve`, could you try that?
Doesn't make a difference.

I'm not super familiar with python, sorry :/

If i rename the file and link to the renamed file, the mkdocs server raises a not found error. So we can be sure it is certainly not refering to the project directory.

**Comment by pawamoy** [comment] 2020-02-25 21:44
> I'm not super familiar with python, sorry :/

No problem :slightly_smiling_face: 

Then try uninstalling your package with `pip uninstall neuronal_network`, and try `PYTHONPATH=. mkdocs serve` again.

**Comment by mSpangenberger** [comment] 2020-02-25 21:47
> Then try uninstalling your package with `pip uninstall neuronal_network`, and try `PYTHONPATH=. mkdocs serve` again.

This does indeed work, thanks!

So whats the solution here, using two different environments, one for my own package and one for mkdocs?

**Comment by pawamoy** [comment] 2020-02-25 22:08
You should be able to work in just one environment. If you set your path or your directory structure right, you can directly execute or import code from your source code, without the need to "install" it. If you're new to Python, I know it can be hard to wrap your head around how Python and virtualenvs work. Maybe you should find resources on the web that explain things better than me?

Maybe I could also recommend [Poetry](https://github.com/python-poetry/poetry), it's a modern tool that helps packaging Python projects, and it manages the virtualenvs for you :+1: !

Closing! (reopen if your issue is not resolved :wink:)

**Closed by pawamoy** 2020-02-25 22:08 UTC
Labels: packaging, question

**Comment by mSpangenberger** [comment] 2020-02-25 22:15
I will look into it, thanks for you help!
